In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [3]:
df = pd.read_csv('iris.csv')
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [7]:
df = df.drop(['Id'],axis=1)


In [8]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [9]:
df['Species'] = df['Species'].map({"Iris-setosa":0,"Iris-versicolor":1,"Iris-virginica":2})

In [12]:
X = df.iloc[: , :-1]
y = df.iloc[: , -1]

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [14]:
X_train.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
96             5.7           2.9            4.2           1.3
105            7.6           3.0            6.6           2.1
66             5.6           3.0            4.5           1.5
0              5.1           3.5            1.4           0.2
122            7.7           2.8            6.7           2.0

In [15]:
y_train.head()

96     1
105    2
66     1
0      0
122    2
Name: Species, dtype: int64

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [17]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import ReLU,LeakyReLU,PReLU,ELU

In [18]:
ann = Sequential()


In [19]:
import warnings
warnings.filterwarnings("ignore")

In [20]:
ann.add(Dense(units=6,kernel_initializer='he_uniform',activation='relu',input_dim=4))
ann.add(Dense(units=6,kernel_initializer='he_uniform',activation='relu'))
ann.add(Dense(units=1,kernel_initializer='glorot_uniform',activation='softmax'))



In [21]:
ann.compile(optimizer='Adamax',loss='categorical_crossentropy',metrics=['accuracy'])


In [23]:
reg = ann.fit(X_train,y_train,validation_split=0.1,batch_size=10,epochs=100)

Epoch 1/100
9/9 [==============================] - 0s 39ms/step - loss: 0.0000e+00 - accuracy: 0.3444 - val_loss: 0.0000e+00 - val_accuracy: 0.4000
Epoch 2/100
9/9 [==============================] - 0s 4ms/step - loss: 0.0000e+00 - accuracy: 0.3444 - val_loss: 0.0000e+00 - val_accuracy: 0.4000
Epoch 3/100
9/9 [==============================] - 0s 4ms/step - loss: 0.0000e+00 - accuracy: 0.3444 - val_loss: 0.0000e+00 - val_accuracy: 0.4000
Epoch 4/100
9/9 [==============================] - 0s 4ms/step - loss: 0.0000e+00 - accuracy: 0.3444 - val_loss: 0.0000e+00 - val_accuracy: 0.4000
Epoch 5/100
9/9 [==============================] - 0s 4ms/step - loss: 0.0000e+00 - accuracy: 0.3444 - val_loss: 0.0000e+00 - val_accuracy: 0.4000
Epoch 6/100
9/9 [==============================] - 0s 4ms/step - loss: 0.0000e+00 - accuracy: 0.3444 - val_loss: 0.0000e+00 - val_accuracy: 0.4000
Epoch 7/100
9/9 [==============================] - 0s 4ms/step - loss: 0.0000e+00 - accuracy: 0.3444 - val_loss: 0.00

In [24]:
y_pred = ann.predict(X_test)
y_pred = y_pred > 0.5

In [27]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [28]:
print(confusion_matrix(y_test,y_pred))


[[ 0 19  0]
 [ 0 15  0]
 [ 0 16  0]]


In [30]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        19
           1       0.30      1.00      0.46        15
           2       0.00      0.00      0.00        16

    accuracy                           0.30        50
   macro avg       0.10      0.33      0.15        50
weighted avg       0.09      0.30      0.14        50



In [93]:
accuracy_score(y_test,y_pred)

0.8681818181818182