In [3]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('../../data_files/Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values



In [2]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [9]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [10]:
# ------ Part-1: Data preprocessing ----------
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder,StandardScaler
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])  # country
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])  # gender


In [12]:
X[0]

array([619, 0, 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [13]:
s = StandardScaler()   # used to scale values from each column based on mean and std deviation.

In [14]:
X1 = s.fit_transform(X)

In [18]:
X1

array([[-0.32622142, -0.90188624, -1.09598752, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-0.44003595,  1.51506738, -1.09598752, ..., -1.54776799,
         0.97024255,  0.21653375],
       [-1.53679418, -0.90188624, -1.09598752, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.60498839, -0.90188624, -1.09598752, ..., -1.54776799,
         0.97024255, -1.00864308],
       [ 1.25683526,  0.30659057,  0.91241915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 1.46377078, -0.90188624, -1.09598752, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [20]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [16]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X1, y, test_size=0.3, random_state=0)


In [17]:
import tensorflow as tf  # dl platform/set of python libraries for deep learning
import keras  # wrapper layer over tensorflow()

Using TensorFlow backend.


In [18]:
X1.shape

(10000, 10)

In [19]:
X_train.shape

(7000, 10)

In [20]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [21]:
# ------- Part-2: Build the ANN --------
# import keras library and packages
import keras
from keras.models import Sequential  # sequential: acts as a container,that holds all the layers of the ANN together.
from keras.layers import Dense  # an ANN  hidden layer.

#activation funtion : is the function f(x): sigmoid(x)/relu(x)/tanh(x) which is present in each neuron, and is responsible for learning non linear patterns.
#its the function responsible for converting input(x1)-->signal  and passing to the next layer.

#kernel initializer : various ways of initializing the weight matrix.

#optimizer : a function g(x): responsible for reducing the loss, and increasing the accuracy of the model.

#loss : a metric to calculate the error from the NN.

# Initializing the ANN

classifier = Sequential()
# Adding the input layer and the first hidden layer
ip_layer = Dense(activation='relu', input_dim=10, kernel_initializer='uniform', units=10)
classifier.add(ip_layer)  # add  layer to container/sequential


# Adding first hidden layer
layer_info = Dense(activation='relu', kernel_initializer='uniform', units=1000)
classifier.add(layer_info)

layer_info = Dense(activation='relu', kernel_initializer='uniform', units=500)
classifier.add(layer_info)


layer_info = Dense(activation='relu', kernel_initializer='uniform', units=250)
classifier.add(layer_info)

layer_info = Dense(activation='relu', kernel_initializer='uniform', units=100)
classifier.add(layer_info)

# Adding output layer
layer_info = Dense(activation='sigmoid', kernel_initializer='uniform', units=1)
classifier.add(layer_info)

# Compiling the ANN
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [23]:
classifier.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_2 (Dense)              (None, 1000)              11000     
_________________________________________________________________
dense_3 (Dense)              (None, 500)               500500    
_________________________________________________________________
dense_4 (Dense)              (None, 250)               125250    
_________________________________________________________________
dense_5 (Dense)              (None, 100)               25100     
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 101       
Total params: 662,061
Trainable params: 662,061
Non-trainable params: 0
________________________________________________

In [25]:
X_train.shape

(7000, 10)

In [26]:
# Fitting the ANN to the training set
classifier.fit(X_train, y_train,batch_size=256, epochs=25)


Epoch 1/25
7000/7000 [==============================] - 1s 191us/step - loss: 0.5776 - accuracy: 0.7786
Epoch 2/25
7000/7000 [==============================] - 1s 134us/step - loss: 0.4602 - accuracy: 0.7977
Epoch 3/25
7000/7000 [==============================] - 1s 176us/step - loss: 0.4329 - accuracy: 0.7977
Epoch 4/25
7000/7000 [==============================] - 1s 186us/step - loss: 0.4217 - accuracy: 0.7977
Epoch 5/25
7000/7000 [==============================] - 1s 141us/step - loss: 0.4051 - accuracy: 0.8211
Epoch 6/25
7000/7000 [==============================] - 1s 138us/step - loss: 0.3727 - accuracy: 0.8513
Epoch 7/25
7000/7000 [==============================] - 1s 135us/step - loss: 0.3605 - accuracy: 0.8529
Epoch 8/25
7000/7000 [==============================] - 1s 160us/step - loss: 0.3590 - accuracy: 0.8554
Epoch 9/25
7000/7000 [==============================] - 1s 155us/step - loss: 0.3544 - accuracy: 0.8561
Epoch 10/25
7000/7000 [==============================] - 1s 126

In [27]:
y_pred=classifier.predict(X_test)

In [31]:
yp=[]
for i in range(len(y_pred)):
    if y_pred[i]< 0.5:
        yp.append(0)
    else:
        yp.append(1)

In [33]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,yp)

0.858

# 